[env]
_.path = ['./node_modules/.bin']

[hooks]
postinstall = 'bun install'

[settings]
experimental = true

[tools]
# https://nodejs.org/en/about/previous-releases
node = "22.19.0"
# https://github.com/biomejs/biome/releases
biome = "2.3.2"
# https://github.com/evilmartians/lefthook/releases
lefthook = "1.13.4"
# https://github.com/oven-sh/bun/releases
bun = "1.3.1"
# https://github.com/microsoft/typescript/releases
"npm:typescript" = "5.9.3"
# https://github.com/antfu-collective/bumpp/releases
"npm:bumpp" = "10.3.1"
