[tools]
# https://nodejs.org/en/about/previous-releases
node = "22.19.0"
# https://github.com/biomejs/biome/releases
biome = "2.3.2"
# https://github.com/oven-sh/bun/releases
bun = "1.3.1"
# https://github.com/antfu-collective/bumpp/releases
bumpp = "10.3.1"
# https://github.com/bunup/bunup/releases
bunup = "0.15.12"
# https://github.com/evilmartians/lefthook/releases
lefthook = "1.13.4"
# https://github.com/microsoft/typescript/releases
typescript = "5.9.3"
